# ------------------------------------------------------------------------------
# Basic configurations
chdir:                /Users/Alex/Code/sinatra-housewarming/
environment:          production
log:                  log/thin.log
pid:                  tmp/pids/thin.pid
# ------------------------------------------------------------------------------
# If running on a TCP port bind configure the following
address:              0.0.0.0
port:                 3000
# ------------------------------------------------------------------------------
# For unix sockets, comment out the TCP stuff and uncomment this
# socket:               tmp/thin.sock
# ------------------------------------------------------------------------------
# Server count => increase with multiple cores
servers:              1
daemonize:            true
# ------------------------------------------------------------------------------
# Performance requirements
timeout:              30
wait:                 30
max_conns:            1024
max_persistent_conns: 512
require:              []
# ------------------------------------------------------------------------------